#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt', "1.7"
cookbook 'build-essential'
cookbook 'rvm', git: 'https://github.com/fnichol/chef-rvm.git'
cookbook 'mongodb'
